from setuptools import setup

setup(
    name='lfmc-api',
    version='0.5.1',
    packages=['lfmc', 'lfmc.log', 'lfmc.query', 'lfmc.config', 'lfmc.models', 'lfmc.library', 'lfmc.monitor',
              'lfmc.process', 'lfmc.results', 'lfmc.resource', 'venv.lib.python3.6.site-packages.pytz',
              'venv.lib.python3.6.site-packages.babel', 'venv.lib.python3.6.site-packages.babel.messages',
              'venv.lib.python3.6.site-packages.babel.localtime', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.linalg',
              'venv.lib.python3.6.site-packages.numpy.linalg.tests', 'venv.lib.python3.6.site-packages.numpy.random',
              'venv.lib.python3.6.site-packages.numpy.random.tests', 'venv.lib.python3.6.site-packages.numpy.testing',
              'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing.nose_tools',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.cartopy',
              'venv.lib.python3.6.site-packages.cartopy.io', 'venv.lib.python3.6.site-packages.cartopy.mpl',
              'venv.lib.python3.6.site-packages.cartopy.tests', 'venv.lib.python3.6.site-packages.cartopy.tests.io',
              'venv.lib.python3.6.site-packages.cartopy.tests.crs',
              'venv.lib.python3.6.site-packages.cartopy.tests.mpl', 'venv.lib.python3.6.site-packages.cartopy.examples',
              'venv.lib.python3.6.site-packages.cartopy.geodesic', 'venv.lib.python3.6.site-packages.cartopy.sphinxext',
              'venv.lib.python3.6.site-packages.shapely', 'venv.lib.python3.6.site-packages.shapely.examples',
              'venv.lib.python3.6.site-packages.shapely.geometry', 'venv.lib.python3.6.site-packages.shapely.speedups',
              'venv.lib.python3.6.site-packages.shapely.algorithms',
              'venv.lib.python3.6.site-packages.shapely.vectorized', 'venv.lib.python3.6.site-packages.setuptools',
              'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.pkg_resources',
              'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='https://lfmc.unimelb.edu.au/',
    license='LGPLv3',
    author='Anthony Rawlins',
    author_email='anthony.rawlins@unimelb.edu.au',
    description=''
)
